// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package pool

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Minter                                          protoreflect.MessageDescriptor
	fd_Minter_provisions                               protoreflect.FieldDescriptor
	fd_Minter_reduction_period_in_epochs               protoreflect.FieldDescriptor
	fd_Minter_minter_type                              protoreflect.FieldDescriptor
	fd_Minter_total_minted                             protoreflect.FieldDescriptor
	fd_Minter_minting_rewards_distribution_start_epoch protoreflect.FieldDescriptor
	fd_Minter_minting_interval                         protoreflect.FieldDescriptor
	fd_Minter_module_account                           protoreflect.FieldDescriptor
	fd_Minter_minter_cap                               protoreflect.FieldDescriptor
	fd_Minter_epoch_identifier                         protoreflect.FieldDescriptor
)

func init() {
	file_qcore_pool_minter_proto_init()
	md_Minter = File_qcore_pool_minter_proto.Messages().ByName("Minter")
	fd_Minter_provisions = md_Minter.Fields().ByName("provisions")
	fd_Minter_reduction_period_in_epochs = md_Minter.Fields().ByName("reduction_period_in_epochs")
	fd_Minter_minter_type = md_Minter.Fields().ByName("minter_type")
	fd_Minter_total_minted = md_Minter.Fields().ByName("total_minted")
	fd_Minter_minting_rewards_distribution_start_epoch = md_Minter.Fields().ByName("minting_rewards_distribution_start_epoch")
	fd_Minter_minting_interval = md_Minter.Fields().ByName("minting_interval")
	fd_Minter_module_account = md_Minter.Fields().ByName("module_account")
	fd_Minter_minter_cap = md_Minter.Fields().ByName("minter_cap")
	fd_Minter_epoch_identifier = md_Minter.Fields().ByName("epoch_identifier")
}

var _ protoreflect.Message = (*fastReflection_Minter)(nil)

type fastReflection_Minter Minter

func (x *Minter) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Minter)(x)
}

func (x *Minter) slowProtoReflect() protoreflect.Message {
	mi := &file_qcore_pool_minter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Minter_messageType fastReflection_Minter_messageType
var _ protoreflect.MessageType = fastReflection_Minter_messageType{}

type fastReflection_Minter_messageType struct{}

func (x fastReflection_Minter_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Minter)(nil)
}
func (x fastReflection_Minter_messageType) New() protoreflect.Message {
	return new(fastReflection_Minter)
}
func (x fastReflection_Minter_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Minter
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Minter) Descriptor() protoreflect.MessageDescriptor {
	return md_Minter
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Minter) Type() protoreflect.MessageType {
	return _fastReflection_Minter_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Minter) New() protoreflect.Message {
	return new(fastReflection_Minter)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Minter) Interface() protoreflect.ProtoMessage {
	return (*Minter)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Minter) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Provisions != "" {
		value := protoreflect.ValueOfString(x.Provisions)
		if !f(fd_Minter_provisions, value) {
			return
		}
	}
	if x.ReductionPeriodInEpochs != uint64(0) {
		value := protoreflect.ValueOfUint64(x.ReductionPeriodInEpochs)
		if !f(fd_Minter_reduction_period_in_epochs, value) {
			return
		}
	}
	if x.MinterType != "" {
		value := protoreflect.ValueOfString(x.MinterType)
		if !f(fd_Minter_minter_type, value) {
			return
		}
	}
	if x.TotalMinted != "" {
		value := protoreflect.ValueOfString(x.TotalMinted)
		if !f(fd_Minter_total_minted, value) {
			return
		}
	}
	if x.MintingRewardsDistributionStartEpoch != uint64(0) {
		value := protoreflect.ValueOfUint64(x.MintingRewardsDistributionStartEpoch)
		if !f(fd_Minter_minting_rewards_distribution_start_epoch, value) {
			return
		}
	}
	if x.MintingInterval != "" {
		value := protoreflect.ValueOfString(x.MintingInterval)
		if !f(fd_Minter_minting_interval, value) {
			return
		}
	}
	if x.ModuleAccount != "" {
		value := protoreflect.ValueOfString(x.ModuleAccount)
		if !f(fd_Minter_module_account, value) {
			return
		}
	}
	if x.MinterCap != "" {
		value := protoreflect.ValueOfString(x.MinterCap)
		if !f(fd_Minter_minter_cap, value) {
			return
		}
	}
	if x.EpochIdentifier != "" {
		value := protoreflect.ValueOfString(x.EpochIdentifier)
		if !f(fd_Minter_epoch_identifier, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Minter) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "qcore.pool.Minter.provisions":
		return x.Provisions != ""
	case "qcore.pool.Minter.reduction_period_in_epochs":
		return x.ReductionPeriodInEpochs != uint64(0)
	case "qcore.pool.Minter.minter_type":
		return x.MinterType != ""
	case "qcore.pool.Minter.total_minted":
		return x.TotalMinted != ""
	case "qcore.pool.Minter.minting_rewards_distribution_start_epoch":
		return x.MintingRewardsDistributionStartEpoch != uint64(0)
	case "qcore.pool.Minter.minting_interval":
		return x.MintingInterval != ""
	case "qcore.pool.Minter.module_account":
		return x.ModuleAccount != ""
	case "qcore.pool.Minter.minter_cap":
		return x.MinterCap != ""
	case "qcore.pool.Minter.epoch_identifier":
		return x.EpochIdentifier != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcore.pool.Minter"))
		}
		panic(fmt.Errorf("message qcore.pool.Minter does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Minter) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "qcore.pool.Minter.provisions":
		x.Provisions = ""
	case "qcore.pool.Minter.reduction_period_in_epochs":
		x.ReductionPeriodInEpochs = uint64(0)
	case "qcore.pool.Minter.minter_type":
		x.MinterType = ""
	case "qcore.pool.Minter.total_minted":
		x.TotalMinted = ""
	case "qcore.pool.Minter.minting_rewards_distribution_start_epoch":
		x.MintingRewardsDistributionStartEpoch = uint64(0)
	case "qcore.pool.Minter.minting_interval":
		x.MintingInterval = ""
	case "qcore.pool.Minter.module_account":
		x.ModuleAccount = ""
	case "qcore.pool.Minter.minter_cap":
		x.MinterCap = ""
	case "qcore.pool.Minter.epoch_identifier":
		x.EpochIdentifier = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcore.pool.Minter"))
		}
		panic(fmt.Errorf("message qcore.pool.Minter does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Minter) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "qcore.pool.Minter.provisions":
		value := x.Provisions
		return protoreflect.ValueOfString(value)
	case "qcore.pool.Minter.reduction_period_in_epochs":
		value := x.ReductionPeriodInEpochs
		return protoreflect.ValueOfUint64(value)
	case "qcore.pool.Minter.minter_type":
		value := x.MinterType
		return protoreflect.ValueOfString(value)
	case "qcore.pool.Minter.total_minted":
		value := x.TotalMinted
		return protoreflect.ValueOfString(value)
	case "qcore.pool.Minter.minting_rewards_distribution_start_epoch":
		value := x.MintingRewardsDistributionStartEpoch
		return protoreflect.ValueOfUint64(value)
	case "qcore.pool.Minter.minting_interval":
		value := x.MintingInterval
		return protoreflect.ValueOfString(value)
	case "qcore.pool.Minter.module_account":
		value := x.ModuleAccount
		return protoreflect.ValueOfString(value)
	case "qcore.pool.Minter.minter_cap":
		value := x.MinterCap
		return protoreflect.ValueOfString(value)
	case "qcore.pool.Minter.epoch_identifier":
		value := x.EpochIdentifier
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcore.pool.Minter"))
		}
		panic(fmt.Errorf("message qcore.pool.Minter does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Minter) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "qcore.pool.Minter.provisions":
		x.Provisions = value.Interface().(string)
	case "qcore.pool.Minter.reduction_period_in_epochs":
		x.ReductionPeriodInEpochs = value.Uint()
	case "qcore.pool.Minter.minter_type":
		x.MinterType = value.Interface().(string)
	case "qcore.pool.Minter.total_minted":
		x.TotalMinted = value.Interface().(string)
	case "qcore.pool.Minter.minting_rewards_distribution_start_epoch":
		x.MintingRewardsDistributionStartEpoch = value.Uint()
	case "qcore.pool.Minter.minting_interval":
		x.MintingInterval = value.Interface().(string)
	case "qcore.pool.Minter.module_account":
		x.ModuleAccount = value.Interface().(string)
	case "qcore.pool.Minter.minter_cap":
		x.MinterCap = value.Interface().(string)
	case "qcore.pool.Minter.epoch_identifier":
		x.EpochIdentifier = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcore.pool.Minter"))
		}
		panic(fmt.Errorf("message qcore.pool.Minter does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Minter) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "qcore.pool.Minter.provisions":
		panic(fmt.Errorf("field provisions of message qcore.pool.Minter is not mutable"))
	case "qcore.pool.Minter.reduction_period_in_epochs":
		panic(fmt.Errorf("field reduction_period_in_epochs of message qcore.pool.Minter is not mutable"))
	case "qcore.pool.Minter.minter_type":
		panic(fmt.Errorf("field minter_type of message qcore.pool.Minter is not mutable"))
	case "qcore.pool.Minter.total_minted":
		panic(fmt.Errorf("field total_minted of message qcore.pool.Minter is not mutable"))
	case "qcore.pool.Minter.minting_rewards_distribution_start_epoch":
		panic(fmt.Errorf("field minting_rewards_distribution_start_epoch of message qcore.pool.Minter is not mutable"))
	case "qcore.pool.Minter.minting_interval":
		panic(fmt.Errorf("field minting_interval of message qcore.pool.Minter is not mutable"))
	case "qcore.pool.Minter.module_account":
		panic(fmt.Errorf("field module_account of message qcore.pool.Minter is not mutable"))
	case "qcore.pool.Minter.minter_cap":
		panic(fmt.Errorf("field minter_cap of message qcore.pool.Minter is not mutable"))
	case "qcore.pool.Minter.epoch_identifier":
		panic(fmt.Errorf("field epoch_identifier of message qcore.pool.Minter is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcore.pool.Minter"))
		}
		panic(fmt.Errorf("message qcore.pool.Minter does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Minter) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "qcore.pool.Minter.provisions":
		return protoreflect.ValueOfString("")
	case "qcore.pool.Minter.reduction_period_in_epochs":
		return protoreflect.ValueOfUint64(uint64(0))
	case "qcore.pool.Minter.minter_type":
		return protoreflect.ValueOfString("")
	case "qcore.pool.Minter.total_minted":
		return protoreflect.ValueOfString("")
	case "qcore.pool.Minter.minting_rewards_distribution_start_epoch":
		return protoreflect.ValueOfUint64(uint64(0))
	case "qcore.pool.Minter.minting_interval":
		return protoreflect.ValueOfString("")
	case "qcore.pool.Minter.module_account":
		return protoreflect.ValueOfString("")
	case "qcore.pool.Minter.minter_cap":
		return protoreflect.ValueOfString("")
	case "qcore.pool.Minter.epoch_identifier":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcore.pool.Minter"))
		}
		panic(fmt.Errorf("message qcore.pool.Minter does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Minter) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in qcore.pool.Minter", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Minter) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Minter) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Minter) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Minter) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Minter)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Provisions)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.ReductionPeriodInEpochs != 0 {
			n += 1 + runtime.Sov(uint64(x.ReductionPeriodInEpochs))
		}
		l = len(x.MinterType)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TotalMinted)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.MintingRewardsDistributionStartEpoch != 0 {
			n += 1 + runtime.Sov(uint64(x.MintingRewardsDistributionStartEpoch))
		}
		l = len(x.MintingInterval)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ModuleAccount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MinterCap)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.EpochIdentifier)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Minter)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.EpochIdentifier) > 0 {
			i -= len(x.EpochIdentifier)
			copy(dAtA[i:], x.EpochIdentifier)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.EpochIdentifier)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.MinterCap) > 0 {
			i -= len(x.MinterCap)
			copy(dAtA[i:], x.MinterCap)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MinterCap)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.ModuleAccount) > 0 {
			i -= len(x.ModuleAccount)
			copy(dAtA[i:], x.ModuleAccount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ModuleAccount)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.MintingInterval) > 0 {
			i -= len(x.MintingInterval)
			copy(dAtA[i:], x.MintingInterval)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MintingInterval)))
			i--
			dAtA[i] = 0x32
		}
		if x.MintingRewardsDistributionStartEpoch != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.MintingRewardsDistributionStartEpoch))
			i--
			dAtA[i] = 0x28
		}
		if len(x.TotalMinted) > 0 {
			i -= len(x.TotalMinted)
			copy(dAtA[i:], x.TotalMinted)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TotalMinted)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.MinterType) > 0 {
			i -= len(x.MinterType)
			copy(dAtA[i:], x.MinterType)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MinterType)))
			i--
			dAtA[i] = 0x1a
		}
		if x.ReductionPeriodInEpochs != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ReductionPeriodInEpochs))
			i--
			dAtA[i] = 0x10
		}
		if len(x.Provisions) > 0 {
			i -= len(x.Provisions)
			copy(dAtA[i:], x.Provisions)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Provisions)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Minter)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Minter: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Minter: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Provisions", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Provisions = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ReductionPeriodInEpochs", wireType)
				}
				x.ReductionPeriodInEpochs = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ReductionPeriodInEpochs |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MinterType", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MinterType = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalMinted", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TotalMinted = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MintingRewardsDistributionStartEpoch", wireType)
				}
				x.MintingRewardsDistributionStartEpoch = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.MintingRewardsDistributionStartEpoch |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MintingInterval", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MintingInterval = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ModuleAccount", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ModuleAccount = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MinterCap", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MinterCap = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EpochIdentifier", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.EpochIdentifier = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: qcore/pool/minter.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Minter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provisions                           string `protobuf:"bytes,1,opt,name=provisions,proto3" json:"provisions,omitempty"`
	ReductionPeriodInEpochs              uint64 `protobuf:"varint,2,opt,name=reduction_period_in_epochs,json=reductionPeriodInEpochs,proto3" json:"reduction_period_in_epochs,omitempty"`
	MinterType                           string `protobuf:"bytes,3,opt,name=minter_type,json=minterType,proto3" json:"minter_type,omitempty"`
	TotalMinted                          string `protobuf:"bytes,4,opt,name=total_minted,json=totalMinted,proto3" json:"total_minted,omitempty"`
	MintingRewardsDistributionStartEpoch uint64 `protobuf:"varint,5,opt,name=minting_rewards_distribution_start_epoch,json=mintingRewardsDistributionStartEpoch,proto3" json:"minting_rewards_distribution_start_epoch,omitempty"`
	MintingInterval                      string `protobuf:"bytes,6,opt,name=minting_interval,json=mintingInterval,proto3" json:"minting_interval,omitempty"`
	ModuleAccount                        string `protobuf:"bytes,7,opt,name=module_account,json=moduleAccount,proto3" json:"module_account,omitempty"`
	MinterCap                            string `protobuf:"bytes,8,opt,name=minter_cap,json=minterCap,proto3" json:"minter_cap,omitempty"`
	EpochIdentifier                      string `protobuf:"bytes,9,opt,name=epoch_identifier,json=epochIdentifier,proto3" json:"epoch_identifier,omitempty"`
}

func (x *Minter) Reset() {
	*x = Minter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qcore_pool_minter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Minter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Minter) ProtoMessage() {}

// Deprecated: Use Minter.ProtoReflect.Descriptor instead.
func (*Minter) Descriptor() ([]byte, []int) {
	return file_qcore_pool_minter_proto_rawDescGZIP(), []int{0}
}

func (x *Minter) GetProvisions() string {
	if x != nil {
		return x.Provisions
	}
	return ""
}

func (x *Minter) GetReductionPeriodInEpochs() uint64 {
	if x != nil {
		return x.ReductionPeriodInEpochs
	}
	return 0
}

func (x *Minter) GetMinterType() string {
	if x != nil {
		return x.MinterType
	}
	return ""
}

func (x *Minter) GetTotalMinted() string {
	if x != nil {
		return x.TotalMinted
	}
	return ""
}

func (x *Minter) GetMintingRewardsDistributionStartEpoch() uint64 {
	if x != nil {
		return x.MintingRewardsDistributionStartEpoch
	}
	return 0
}

func (x *Minter) GetMintingInterval() string {
	if x != nil {
		return x.MintingInterval
	}
	return ""
}

func (x *Minter) GetModuleAccount() string {
	if x != nil {
		return x.ModuleAccount
	}
	return ""
}

func (x *Minter) GetMinterCap() string {
	if x != nil {
		return x.MinterCap
	}
	return ""
}

func (x *Minter) GetEpochIdentifier() string {
	if x != nil {
		return x.EpochIdentifier
	}
	return ""
}

var File_qcore_pool_minter_proto protoreflect.FileDescriptor

var file_qcore_pool_minter_proto_rawDesc = []byte{
	0x0a, 0x17, 0x71, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x6d, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x71, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x03, 0x0a, 0x06,
	0x4d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3b, 0x0a, 0x1a, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x69, 0x6e, 0x5f, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x17, 0x72, 0x65, 0x64, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x49, 0x6e, 0x45, 0x70, 0x6f,
	0x63, 0x68, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x69,
	0x6e, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x4d, 0x69, 0x6e, 0x74, 0x65, 0x64, 0x12, 0x56, 0x0a, 0x28, 0x6d, 0x69, 0x6e, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x24, 0x6d, 0x69, 0x6e, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12,
	0x29, 0x0a, 0x10, 0x6d, 0x69, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d, 0x69, 0x6e, 0x74, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x70, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x61, 0x70,
	0x12, 0x29, 0x0a, 0x10, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x70, 0x6f, 0x63,
	0x68, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x42, 0x91, 0x01, 0x0a, 0x0e,
	0x63, 0x6f, 0x6d, 0x2e, 0x71, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x42, 0x0b,
	0x4d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x29, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x6c, 0x61, 0x62, 0x73, 0x2d,
	0x78, 0x79, 0x7a, 0x2f, 0x71, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0xa2, 0x02, 0x03, 0x51, 0x50, 0x58, 0xaa, 0x02,
	0x0a, 0x51, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x6f, 0x6f, 0x6c, 0xca, 0x02, 0x0a, 0x51, 0x63,
	0x6f, 0x72, 0x65, 0x5c, 0x50, 0x6f, 0x6f, 0x6c, 0xe2, 0x02, 0x16, 0x51, 0x63, 0x6f, 0x72, 0x65,
	0x5c, 0x50, 0x6f, 0x6f, 0x6c, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0b, 0x51, 0x63, 0x6f, 0x72, 0x65, 0x3a, 0x3a, 0x50, 0x6f, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qcore_pool_minter_proto_rawDescOnce sync.Once
	file_qcore_pool_minter_proto_rawDescData = file_qcore_pool_minter_proto_rawDesc
)

func file_qcore_pool_minter_proto_rawDescGZIP() []byte {
	file_qcore_pool_minter_proto_rawDescOnce.Do(func() {
		file_qcore_pool_minter_proto_rawDescData = protoimpl.X.CompressGZIP(file_qcore_pool_minter_proto_rawDescData)
	})
	return file_qcore_pool_minter_proto_rawDescData
}

var file_qcore_pool_minter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_qcore_pool_minter_proto_goTypes = []interface{}{
	(*Minter)(nil), // 0: qcore.pool.Minter
}
var file_qcore_pool_minter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qcore_pool_minter_proto_init() }
func file_qcore_pool_minter_proto_init() {
	if File_qcore_pool_minter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qcore_pool_minter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Minter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qcore_pool_minter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qcore_pool_minter_proto_goTypes,
		DependencyIndexes: file_qcore_pool_minter_proto_depIdxs,
		MessageInfos:      file_qcore_pool_minter_proto_msgTypes,
	}.Build()
	File_qcore_pool_minter_proto = out.File
	file_qcore_pool_minter_proto_rawDesc = nil
	file_qcore_pool_minter_proto_goTypes = nil
	file_qcore_pool_minter_proto_depIdxs = nil
}
