// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qcore/pool/emission.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Emission struct {
	BlockNumber       string `protobuf:"bytes,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TotalEmission     string `protobuf:"bytes,3,opt,name=total_emission,json=totalEmission,proto3" json:"total_emission,omitempty"`
	EmissionTimestamp string `protobuf:"bytes,4,opt,name=emission_timestamp,json=emissionTimestamp,proto3" json:"emission_timestamp,omitempty"`
}

func (m *Emission) Reset()         { *m = Emission{} }
func (m *Emission) String() string { return proto.CompactTextString(m) }
func (*Emission) ProtoMessage()    {}
func (*Emission) Descriptor() ([]byte, []int) {
	return fileDescriptor_b349f9670349164f, []int{0}
}
func (m *Emission) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Emission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Emission.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Emission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emission.Merge(m, src)
}
func (m *Emission) XXX_Size() int {
	return m.Size()
}
func (m *Emission) XXX_DiscardUnknown() {
	xxx_messageInfo_Emission.DiscardUnknown(m)
}

var xxx_messageInfo_Emission proto.InternalMessageInfo

func (m *Emission) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *Emission) GetTotalEmission() string {
	if m != nil {
		return m.TotalEmission
	}
	return ""
}

func (m *Emission) GetEmissionTimestamp() string {
	if m != nil {
		return m.EmissionTimestamp
	}
	return ""
}

func init() {
	proto.RegisterType((*Emission)(nil), "qcore.pool.Emission")
}

func init() { proto.RegisterFile("qcore/pool/emission.proto", fileDescriptor_b349f9670349164f) }

var fileDescriptor_b349f9670349164f = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x4c, 0xce, 0x2f,
	0x4a, 0xd5, 0x2f, 0xc8, 0xcf, 0xcf, 0xd1, 0x4f, 0xcd, 0xcd, 0x2c, 0x2e, 0xce, 0xcc, 0xcf, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x4b, 0xe9, 0x81, 0xa4, 0x94, 0x9a, 0x19, 0xb9,
	0x38, 0x5c, 0xa1, 0xd2, 0x42, 0x8a, 0x5c, 0x3c, 0x49, 0x39, 0xf9, 0xc9, 0xd9, 0xf1, 0x79, 0xa5,
	0xb9, 0x49, 0xa9, 0x45, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xdc, 0x60, 0x31, 0x3f, 0xb0,
	0x90, 0x90, 0x2a, 0x17, 0x5f, 0x49, 0x7e, 0x49, 0x62, 0x4e, 0x3c, 0xcc, 0x4c, 0x09, 0x66, 0xb0,
	0x22, 0x5e, 0xb0, 0x28, 0xdc, 0x24, 0x5d, 0x2e, 0x21, 0x98, 0x82, 0xf8, 0x92, 0xcc, 0xdc, 0xd4,
	0xe2, 0x92, 0xc4, 0xdc, 0x02, 0x09, 0x16, 0xb0, 0x52, 0x41, 0x98, 0x4c, 0x08, 0x4c, 0xc2, 0xc9,
	0xe9, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58,
	0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x34, 0xd2, 0x33, 0x4b, 0x32,
	0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xf3, 0x4b, 0x4b, 0x92, 0x52, 0x21, 0xa4, 0x6e, 0x5e,
	0x7e, 0x4a, 0xaa, 0x7e, 0x05, 0xc4, 0x7b, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0x60, 0xcf,
	0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x5d, 0xc1, 0x0b, 0xf9, 0x00, 0x00, 0x00,
}

func (m *Emission) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Emission) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Emission) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EmissionTimestamp) > 0 {
		i -= len(m.EmissionTimestamp)
		copy(dAtA[i:], m.EmissionTimestamp)
		i = encodeVarintEmission(dAtA, i, uint64(len(m.EmissionTimestamp)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TotalEmission) > 0 {
		i -= len(m.TotalEmission)
		copy(dAtA[i:], m.TotalEmission)
		i = encodeVarintEmission(dAtA, i, uint64(len(m.TotalEmission)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BlockNumber) > 0 {
		i -= len(m.BlockNumber)
		copy(dAtA[i:], m.BlockNumber)
		i = encodeVarintEmission(dAtA, i, uint64(len(m.BlockNumber)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func encodeVarintEmission(dAtA []byte, offset int, v uint64) int {
	offset -= sovEmission(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Emission) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BlockNumber)
	if l > 0 {
		n += 1 + l + sovEmission(uint64(l))
	}
	l = len(m.TotalEmission)
	if l > 0 {
		n += 1 + l + sovEmission(uint64(l))
	}
	l = len(m.EmissionTimestamp)
	if l > 0 {
		n += 1 + l + sovEmission(uint64(l))
	}
	return n
}

func sovEmission(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEmission(x uint64) (n int) {
	return sovEmission(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Emission) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Emission: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Emission: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalEmission", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalEmission = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmissionTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EmissionTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEmission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEmission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEmission(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEmission
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEmission
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEmission
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEmission
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEmission        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEmission          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEmission = fmt.Errorf("proto: unexpected end of group")
)
