// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qcore/pool/minted.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Minted struct {
	TotalMinted string `protobuf:"bytes,1,opt,name=total_minted,json=totalMinted,proto3" json:"total_minted,omitempty"`
}

func (m *Minted) Reset()         { *m = Minted{} }
func (m *Minted) String() string { return proto.CompactTextString(m) }
func (*Minted) ProtoMessage()    {}
func (*Minted) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fef94d8fa575423, []int{0}
}
func (m *Minted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Minted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Minted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Minted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Minted.Merge(m, src)
}
func (m *Minted) XXX_Size() int {
	return m.Size()
}
func (m *Minted) XXX_DiscardUnknown() {
	xxx_messageInfo_Minted.DiscardUnknown(m)
}

var xxx_messageInfo_Minted proto.InternalMessageInfo

func (m *Minted) GetTotalMinted() string {
	if m != nil {
		return m.TotalMinted
	}
	return ""
}

func init() {
	proto.RegisterType((*Minted)(nil), "qcore.pool.Minted")
}

func init() { proto.RegisterFile("qcore/pool/minted.proto", fileDescriptor_6fef94d8fa575423) }

var fileDescriptor_6fef94d8fa575423 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8f, 0xb1, 0x4a, 0x3b, 0x41,
	0x10, 0xc6, 0x6f, 0x9b, 0xc0, 0xff, 0xfe, 0x56, 0x41, 0x50, 0x82, 0x2c, 0x6a, 0x15, 0x14, 0x6f,
	0x08, 0xbe, 0x41, 0x7a, 0x1b, 0x4b, 0x1b, 0xd9, 0xbd, 0x0c, 0xeb, 0xc2, 0xdd, 0x7e, 0x9b, 0xdb,
	0x39, 0x31, 0x6f, 0xe1, 0x63, 0x59, 0xa6, 0xb4, 0x94, 0xbb, 0x17, 0x91, 0xec, 0xda, 0x0c, 0xc3,
	0xf7, 0xfb, 0xc1, 0x37, 0x53, 0x5f, 0xec, 0x5b, 0x0c, 0x4c, 0x11, 0xe8, 0xa8, 0xf7, 0x41, 0x78,
	0xd7, 0xc4, 0x01, 0x82, 0x65, 0x9d, 0x41, 0x73, 0x02, 0xab, 0x73, 0x07, 0x87, 0x1c, 0xd3, 0x69,
	0x2b, 0xc6, 0xea, 0xca, 0x01, 0xae, 0x63, 0x32, 0xd1, 0x93, 0x09, 0x01, 0x62, 0xc4, 0x23, 0xa4,
	0x3f, 0x7a, 0xd7, 0x22, 0xf5, 0x48, 0x64, 0x4d, 0x62, 0xda, 0x8f, 0x3c, 0x1c, 0xe8, 0x7d, 0x63,
	0x59, 0xcc, 0x86, 0xa2, 0x71, 0x3e, 0x64, 0xb9, 0xb8, 0xb7, 0xf7, 0xf5, 0xe2, 0x29, 0x77, 0x2f,
	0x6f, 0xea, 0x33, 0x81, 0x98, 0xee, 0xb5, 0xdc, 0x72, 0xa9, 0xae, 0xd5, 0xfa, 0xdf, 0xf3, 0xff,
	0x9c, 0x15, 0x65, 0xbb, 0xfd, 0x9a, 0xb4, 0x3a, 0x4e, 0x5a, 0xfd, 0x4c, 0x5a, 0x7d, 0xce, 0xba,
	0x3a, 0xce, 0xba, 0xfa, 0x9e, 0x75, 0xf5, 0xb2, 0x76, 0x5e, 0xde, 0x46, 0xdb, 0xb4, 0xe8, 0x09,
	0xa3, 0x58, 0x2e, 0xf3, 0x21, 0x60, 0xc7, 0xf4, 0x51, 0x7e, 0x94, 0x43, 0xe4, 0x64, 0x17, 0xb9,
	0xf7, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x12, 0x3f, 0x7f, 0xc6, 0xfe, 0x00, 0x00, 0x00,
}

func (m *Minted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Minted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Minted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalMinted) > 0 {
		i -= len(m.TotalMinted)
		copy(dAtA[i:], m.TotalMinted)
		i = encodeVarintMinted(dAtA, i, uint64(len(m.TotalMinted)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMinted(dAtA []byte, offset int, v uint64) int {
	offset -= sovMinted(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Minted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TotalMinted)
	if l > 0 {
		n += 1 + l + sovMinted(uint64(l))
	}
	return n
}

func sovMinted(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMinted(x uint64) (n int) {
	return sovMinted(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Minted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMinted
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Minted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Minted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinted
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMinted
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMinted
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalMinted = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMinted(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMinted
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMinted(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMinted
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMinted
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMinted
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMinted
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMinted
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMinted
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMinted        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMinted          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMinted = fmt.Errorf("proto: unexpected end of group")
)
